#pragma once

#include <algorithm>
#include <map>
#include <numeric>
#include <stdexcept>
#include <utility>
#include <vector>

#include "graphos/core/coboundary.hpp"
#include "graphos/core/complex.hpp"

namespace graphos {

struct CutResult {
  Complex complex;
  // Sized by the RESULT complex: ancestor.index[k][cell] is the cell this one
  // descends from (itself for originals, the split cell for copies). Copies
  // inherit orientation, so all signs are +1. Cochain transport after a cut
  // is a gather through this map.
  ChainMap ancestor;
};

namespace detail {

struct UnionFind {
  std::vector<int> parent;
  explicit UnionFind(int n) : parent(static_cast<std::size_t>(n)) {
    std::iota(parent.begin(), parent.end(), 0);
  }
  int find(int a) {
    while (parent[static_cast<std::size_t>(a)] != a) {
      parent[static_cast<std::size_t>(a)] = parent[static_cast<std::size_t>(parent[static_cast<std::size_t>(a)])];
      a = parent[static_cast<std::size_t>(a)];
    }
    return a;
  }
  void unite(int a, int b) {
    a = find(a);
    b = find(b);
    if (a != b) parent[static_cast<std::size_t>(b)] = a;
  }
};

// Bookkeeping for one cell that splits: which side (component of its cut
// star) each top-dimensional coface belongs to, one representative top cell
// per side, and the result index of each side's copy.
struct SplitInfo {
  std::map<Index, int> side_of_top;
  std::vector<Index> rep_top;
  std::vector<Index> copy_index;
};

}  // namespace detail

// Cuts the complex along the subcomplex generated by the given (n-1)-cells
// (the interface): the combinatorial core of fracture insertion / conformity
// cutting between subdomains.
//
// For every cell x in the closure of the interface, the sides of the cut at x
// are the connected components of x's top-cell star, where two n-cells are
// adjacent iff they share an (n-1)-cell that contains x and is NOT in the
// interface. Each side gets its own copy of x, and the bulk rewires to the
// copies; the ORIGINALS survive untouched as a detached lower-dimensional
// subcomplex — the interface (fracture) domain, closure included. Cells with
// a single side (the tip/rim of the interface) are not copied, which yields
// the crack-front topology automatically; junction cells with three or more
// sides get one copy each, which no two-sided geometric test can express.
//
// No cell is removed and original indices are stable: copies are appended
// after the originals of each stratum, ordered by (ancestor index, side).
//
// Side classification is topological, so the op needs no geometric input.
// Cells whose cofaces do not reach the top dimension (maximal lower-dim
// cells hanging on a split cell) keep their original references and thus
// stay attached to the interface domain.
inline CutResult cut_along(const Complex& c, const std::vector<Index>& interface_cells) {
  const int n = c.dim();
  if (n < 1) throw std::invalid_argument("cut_along: complex must have dimension >= 1");

  // interface + downward closure flags
  std::vector<std::vector<char>> in_closure(static_cast<std::size_t>(n) + 1);
  for (int k = 0; k <= n; ++k) {
    in_closure[static_cast<std::size_t>(k)].assign(static_cast<std::size_t>(c.count(k)), 0);
  }
  for (const Index x : interface_cells) {
    if (x < 0 || x >= c.count(n - 1)) {
      throw std::out_of_range("cut_along: interface cell index out of range");
    }
    in_closure[static_cast<std::size_t>(n) - 1][static_cast<std::size_t>(x)] = 1;
  }
  for (int k = n - 1; k >= 1; --k) {
    const BoundaryOperator& bnd = c.boundary(k);
    for (Index e = 0; e < c.count(k); ++e) {
      if (!in_closure[static_cast<std::size_t>(k)][static_cast<std::size_t>(e)]) continue;
      for (Index m = bnd.offsets[e]; m < bnd.offsets[e + 1]; ++m) {
        in_closure[static_cast<std::size_t>(k) - 1][static_cast<std::size_t>(bnd.indices[m])] = 1;
      }
    }
  }
  const std::vector<char>& in_interface = in_closure[static_cast<std::size_t>(n) - 1];

  std::vector<CoboundaryOperator> cob(static_cast<std::size_t>(n));
  for (int k = 0; k < n; ++k) cob[static_cast<std::size_t>(k)] = coboundary(c, k);

  // cofaces of x at the target dimension, by breadth-first ascent
  const auto up = [&](int k, Index x, int target) {
    std::vector<Index> cur{x};
    for (int level = k; level < target; ++level) {
      const CoboundaryOperator& a = cob[static_cast<std::size_t>(level)];
      std::vector<Index> nxt;
      for (const Index e : cur) {
        for (Index m = a.offsets[static_cast<std::size_t>(e)];
             m < a.offsets[static_cast<std::size_t>(e) + 1]; ++m) {
          nxt.push_back(a.indices[static_cast<std::size_t>(m)]);
        }
      }
      std::sort(nxt.begin(), nxt.end());
      nxt.erase(std::unique(nxt.begin(), nxt.end()), nxt.end());
      cur = std::move(nxt);
    }
    return cur;
  };

  // side classification for every closure cell
  std::vector<std::map<Index, detail::SplitInfo>> split(static_cast<std::size_t>(n) + 1);
  for (int k = n - 1; k >= 0; --k) {
    const std::size_t sk = static_cast<std::size_t>(k);
    for (Index x = 0; x < c.count(k); ++x) {
      if (!in_closure[sk][static_cast<std::size_t>(x)]) continue;
      const std::vector<Index> tops = up(k, x, n);
      if (tops.empty()) continue;
      const std::vector<Index> facets = (k == n - 1) ? std::vector<Index>{x} : up(k, x, n - 1);

      std::map<Index, int> slot;
      for (std::size_t t = 0; t < tops.size(); ++t) slot[tops[t]] = static_cast<int>(t);
      detail::UnionFind uf(static_cast<int>(tops.size()));
      for (const Index f : facets) {
        if (in_interface[static_cast<std::size_t>(f)]) continue;
        const CoboundaryOperator& a = cob[static_cast<std::size_t>(n) - 1];
        const Index lo = a.offsets[static_cast<std::size_t>(f)];
        const Index hi = a.offsets[static_cast<std::size_t>(f) + 1];
        for (Index m = lo + 1; m < hi; ++m) {
          uf.unite(slot[a.indices[static_cast<std::size_t>(lo)]],
                   slot[a.indices[static_cast<std::size_t>(m)]]);
        }
      }

      detail::SplitInfo info;
      std::map<int, int> root_to_side;
      for (std::size_t t = 0; t < tops.size(); ++t) {
        const int root = uf.find(static_cast<int>(t));
        auto [it, fresh] = root_to_side.try_emplace(root, static_cast<int>(info.rep_top.size()));
        if (fresh) info.rep_top.push_back(tops[t]);
        info.side_of_top[tops[t]] = it->second;
      }
      const bool is_interface_cell = (k == n - 1);
      if (is_interface_cell || info.rep_top.size() >= 2) {
        split[sk].emplace(x, std::move(info));
      }
    }
  }

  // allocate copy indices, appended after the originals of each stratum
  std::vector<Index> new_counts = c.counts();
  for (int k = 0; k <= n; ++k) {
    const std::size_t sk = static_cast<std::size_t>(k);
    for (auto& [x, info] : split[sk]) {
      (void)x;
      for (std::size_t s = 0; s < info.rep_top.size(); ++s) {
        info.copy_index.push_back(new_counts[sk]++);
      }
    }
  }

  // a boundary reference to a split cell resolves to the copy for the side
  // that the referencing cell's top-dimensional ancestry lies on
  const auto resolve = [&](int face_dim, Index face, Index top_rep) -> Index {
    const auto it = split[static_cast<std::size_t>(face_dim)].find(face);
    if (it == split[static_cast<std::size_t>(face_dim)].end()) return face;
    const detail::SplitInfo& info = it->second;
    const auto side = info.side_of_top.find(top_rep);
    if (side == info.side_of_top.end()) return face;
    return info.copy_index[static_cast<std::size_t>(side->second)];
  };

  std::vector<BoundaryOperator> strata(static_cast<std::size_t>(n) + 1);
  std::vector<Index> row_idx;
  std::vector<Sign> row_sg;
  for (int k = 1; k <= n; ++k) {
    const std::size_t sk = static_cast<std::size_t>(k);
    const BoundaryOperator& bnd = c.boundary(k);
    BoundaryOperator& out = strata[sk];

    // originals: closure cells keep their rows (they ARE the interface
    // domain); bulk cells rewire references to split faces
    for (Index e = 0; e < c.count(k); ++e) {
      row_idx.clear();
      row_sg.clear();
      Index top_rep = invalid_index;
      const bool is_closure = in_closure[sk][static_cast<std::size_t>(e)];
      for (Index m = bnd.offsets[e]; m < bnd.offsets[e + 1]; ++m) {
        Index f = bnd.indices[m];
        if (!is_closure && split[sk - 1].count(f) != 0) {
          if (top_rep == invalid_index) {
            const std::vector<Index> tops = (k == n) ? std::vector<Index>{e} : up(k, e, n);
            top_rep = tops.empty() ? invalid_index : tops.front();
          }
          if (top_rep != invalid_index) f = resolve(k - 1, f, top_rep);
        }
        row_idx.push_back(f);
        row_sg.push_back(bnd.signs[m]);
      }
      out.append_row(row_idx, row_sg);
    }

    // copies: one row per side, faces resolved through that side's
    // representative top cell (side components refine downward, so the
    // representative determines the face's copy consistently)
    for (const auto& [x, info] : split[sk]) {
      for (std::size_t s = 0; s < info.rep_top.size(); ++s) {
        row_idx.clear();
        row_sg.clear();
        for (Index m = bnd.offsets[x]; m < bnd.offsets[x + 1]; ++m) {
          row_idx.push_back(resolve(k - 1, bnd.indices[m], info.rep_top[s]));
          row_sg.push_back(bnd.signs[m]);
        }
        out.append_row(row_idx, row_sg);
      }
    }
  }

  ChainMap ancestor = ChainMap::sized(new_counts);
  for (int k = 0; k <= n; ++k) {
    const std::size_t sk = static_cast<std::size_t>(k);
    for (Index i = 0; i < c.count(k); ++i) ancestor.index[sk][static_cast<std::size_t>(i)] = i;
    for (const auto& [x, info] : split[sk]) {
      for (const Index copy : info.copy_index) {
        ancestor.index[sk][static_cast<std::size_t>(copy)] = x;
      }
    }
  }

  return CutResult{Complex(std::move(new_counts), std::move(strata)), std::move(ancestor)};
}

}  // namespace graphos
