#pragma once

#include <map>
#include <stdexcept>
#include <utility>
#include <vector>

#include "graphos/core/complex.hpp"
#include "graphos/core/incidence.hpp"
#include "graphos/core/marker.hpp"
#include "graphos/core/union_find.hpp"

namespace graphos {

struct CutResult {
  Complex complex;
  // Sized by the result: ancestor.index[k][σ] is the cell σ descends from —
  // itself for an original, the split cell for a copy. Copies inherit
  // orientation, so all signs are +1. Cochain transport is a gather through
  // this map.
  ChainMap ancestor;
};

namespace detail {

// One splitting cell: the side of each cell of its cut star, a representative
// star cell per side, and the result index of each side's copy.
struct SplitInfo {
  std::map<std::pair<int, Index>, int> side_of;
  std::vector<std::pair<int, Index>> rep;
  std::vector<Index> copy_index;
};

}  // namespace detail

// Cuts along the subcomplex S generated by the marked facets: the
// combinatorial core of fracture insertion and of cutting between subdomains.
// The cut is the union of all ranks' marks.
//
// For each x ∈ cl(S) the sides at x are the incidence-connected components of
// st(x) ∖ cl(S), two star cells connected when one is a face of the other.
// Connectivity runs through cells of every dimension, which is what makes the
// operation sound on non-manifold and mixed-dimensional complexes, where
// facet-only adjacency undercounts. Each side receives its own copy of x, and
// every cell outside cl(S) lies in exactly one side of each split cell it
// references and rewires to that copy.
//
// The originals survive as a detached lower-dimensional subcomplex — the
// interface with its closure. A cell with one side (the rim) is not copied,
// which gives the crack-front topology; a junction cell with three or more
// sides gets one copy each, which no two-sided geometric test can express.
//
// No cell is removed and original indices are stable: copies are appended per
// stratum, ordered by (ancestor, side). Side classification is topological;
// no geometric input is needed.
inline CutResult cut_along(const Complex& c, const Marker& interface) {
  const int n = c.dim();
  if (n < 1) throw std::invalid_argument("cut_along: complex must have dimension >= 1");
  interface.validate_for(c);
  for (int k = 0; k <= n; ++k) {
    if (k != n - 1 && interface.marked_count(k) != 0) {
      throw std::invalid_argument("cut_along: interface marker must mark only (n-1)-cells");
    }
  }

  // interface and downward-closure flags
  std::vector<std::vector<char>> in_closure(static_cast<std::size_t>(n) + 1);
  for (int k = 0; k <= n; ++k) {
    in_closure[static_cast<std::size_t>(k)].assign(static_cast<std::size_t>(c.count(k)), 0);
  }
  {
    const std::vector<char>& f = interface.flags(n - 1);
    for (Index x = 0; x < c.count(n - 1); ++x) {
      in_closure[static_cast<std::size_t>(n) - 1][static_cast<std::size_t>(x)] =
          f[static_cast<std::size_t>(x)];
    }
  }
  for (int k = n - 1; k >= 1; --k) {
    const BoundaryOperator& bnd = c.boundary(k);
    for (Index e = 0; e < c.count(k); ++e) {
      if (!in_closure[static_cast<std::size_t>(k)][static_cast<std::size_t>(e)]) continue;
      for (Index m = bnd.offsets[e]; m < bnd.offsets[e + 1]; ++m) {
        in_closure[static_cast<std::size_t>(k) - 1][static_cast<std::size_t>(bnd.indices[m])] = 1;
      }
    }
  }

  // coface tables for the star traversal
  std::vector<std::vector<Adjacency>> inc(static_cast<std::size_t>(n) + 1);
  for (int k = 0; k < n; ++k) {
    inc[static_cast<std::size_t>(k)].resize(static_cast<std::size_t>(n) + 1);
    for (int j = k + 1; j <= n; ++j) {
      inc[static_cast<std::size_t>(k)][static_cast<std::size_t>(j)] = incidence(c, k, j);
    }
  }

  // sides of every closure cell
  std::vector<std::map<Index, detail::SplitInfo>> split(static_cast<std::size_t>(n) + 1);
  std::vector<std::pair<int, Index>> nodes;
  for (int k = 0; k < n; ++k) {
    const std::size_t sk = static_cast<std::size_t>(k);
    for (Index x = 0; x < c.count(k); ++x) {
      if (!in_closure[sk][static_cast<std::size_t>(x)]) continue;

      // the cut star: strict cofaces of x outside cl(S)
      nodes.clear();
      for (int j = k + 1; j <= n; ++j) {
        const Adjacency& a = inc[sk][static_cast<std::size_t>(j)];
        for (Index m = a.offsets[static_cast<std::size_t>(x)];
             m < a.offsets[static_cast<std::size_t>(x) + 1]; ++m) {
          const Index y = a.indices[static_cast<std::size_t>(m)];
          if (!in_closure[static_cast<std::size_t>(j)][static_cast<std::size_t>(y)]) {
            nodes.emplace_back(j, y);
          }
        }
      }
      if (nodes.empty()) continue;

      std::map<std::pair<int, Index>, int> slot;
      for (std::size_t t = 0; t < nodes.size(); ++t) slot[nodes[t]] = static_cast<int>(t);
      UnionFind uf(static_cast<Index>(nodes.size()));
      // two star cells are connected when one bounds the other:
      // comparability in the face poset, not direct-face links alone, since
      // open cells meet whenever z < y even if every intermediate cell lies
      // in cl(S)
      for (std::size_t t = 0; t < nodes.size(); ++t) {
        const auto [jz, z] = nodes[t];
        for (int j2 = jz + 1; j2 <= n; ++j2) {
          const Adjacency& a2 = inc[static_cast<std::size_t>(jz)][static_cast<std::size_t>(j2)];
          for (Index m = a2.offsets[static_cast<std::size_t>(z)];
               m < a2.offsets[static_cast<std::size_t>(z) + 1]; ++m) {
            const auto it = slot.find({j2, a2.indices[static_cast<std::size_t>(m)]});
            if (it != slot.end()) {
              uf.unite(static_cast<Index>(t), static_cast<Index>(it->second));
            }
          }
        }
      }

      detail::SplitInfo info;
      std::map<Index, int> root_to_side;
      for (std::size_t t = 0; t < nodes.size(); ++t) {
        const Index root = uf.find(static_cast<Index>(t));
        auto [it, fresh] = root_to_side.try_emplace(root, static_cast<int>(info.rep.size()));
        if (fresh) info.rep.push_back(nodes[t]);
        info.side_of[nodes[t]] = it->second;
      }
      // duplicate when the cell is the interface itself, has several sides,
      // or has any duplicated face — ascending in k, so lower strata are
      // final. The last clause keeps a one-sided rim cell consistent when its
      // vertex splits: the bulk rewires to the copy, the interface keeps the
      // original. Crack-front cells — one side, no split face — stay shared.
      bool needs_copy = (k == n - 1) || info.rep.size() >= 2;
      if (!needs_copy && k >= 1) {
        const BoundaryOperator& bx = c.boundary(k);
        for (Index m = bx.offsets[x]; m < bx.offsets[x + 1] && !needs_copy; ++m) {
          needs_copy = split[sk - 1].count(bx.indices[m]) != 0;
        }
      }
      if (needs_copy) {
        split[sk].emplace(x, std::move(info));
      }
    }
  }

  // copy indices, appended after the originals of each stratum
  std::vector<Index> new_counts = c.counts();
  for (int k = 0; k <= n; ++k) {
    const std::size_t sk = static_cast<std::size_t>(k);
    for (auto& [x, info] : split[sk]) {
      (void)x;
      for (std::size_t s = 0; s < info.rep.size(); ++s) {
        info.copy_index.push_back(new_counts[sk]++);
      }
    }
  }

  // a reference to a split cell resolves to the copy of the side the
  // referencing cell lies on; it is in that cell's cut star by construction
  const auto resolve = [&split](int face_dim, Index face, int ref_dim, Index ref) -> Index {
    const auto it = split[static_cast<std::size_t>(face_dim)].find(face);
    if (it == split[static_cast<std::size_t>(face_dim)].end()) return face;
    const auto side = it->second.side_of.find({ref_dim, ref});
    if (side == it->second.side_of.end()) return face;
    return it->second.copy_index[static_cast<std::size_t>(side->second)];
  };

  std::vector<BoundaryOperator> strata(static_cast<std::size_t>(n) + 1);
  std::vector<Index> row_idx;
  std::vector<Sign> row_sg;
  for (int k = 1; k <= n; ++k) {
    const std::size_t sk = static_cast<std::size_t>(k);
    const BoundaryOperator& bnd = c.boundary(k);
    BoundaryOperator& out = strata[sk];

    // originals: cl(S) keeps its rows, being the interface; everything else
    // rewires references to split faces through its own side
    for (Index e = 0; e < c.count(k); ++e) {
      row_idx.clear();
      row_sg.clear();
      const bool is_closure = in_closure[sk][static_cast<std::size_t>(e)];
      for (Index m = bnd.offsets[e]; m < bnd.offsets[e + 1]; ++m) {
        Index f = bnd.indices[m];
        if (!is_closure) f = resolve(k - 1, f, k, e);
        row_idx.push_back(f);
        row_sg.push_back(bnd.signs[m]);
      }
      out.append_row(row_idx, row_sg);
    }

    // copies: one row per side, faces resolved through that side's
    // representative star cell. Side components refine downward, so the
    // representative determines each face's copy consistently.
    for (const auto& [x, info] : split[sk]) {
      for (std::size_t s = 0; s < info.rep.size(); ++s) {
        const auto [rd, ri] = info.rep[s];
        row_idx.clear();
        row_sg.clear();
        for (Index m = bnd.offsets[x]; m < bnd.offsets[x + 1]; ++m) {
          row_idx.push_back(resolve(k - 1, bnd.indices[m], rd, ri));
          row_sg.push_back(bnd.signs[m]);
        }
        out.append_row(row_idx, row_sg);
      }
    }
  }

  ChainMap ancestor = ChainMap::sized(new_counts);
  for (int k = 0; k <= n; ++k) {
    const std::size_t sk = static_cast<std::size_t>(k);
    for (Index i = 0; i < c.count(k); ++i) ancestor.index[sk][static_cast<std::size_t>(i)] = i;
    for (const auto& [x, info] : split[sk]) {
      for (const Index copy : info.copy_index) {
        ancestor.index[sk][static_cast<std::size_t>(copy)] = x;
      }
    }
  }

  return CutResult{Complex(std::move(new_counts), std::move(strata)), std::move(ancestor)};
}

}  // namespace graphos
