#pragma once

#include <utility>
#include <vector>

#include "graphos/core/complex.hpp"
#include "graphos/ops/disjoint_union.hpp"
#include "graphos/ops/quotient.hpp"

namespace graphos {

struct PushoutResult {
  Complex complex;
  ChainMap a_map;  // cells of A into the pushout
  ChainMap b_map;  // cells of B into the pushout
};

// The pushout A ⊔_C B: the union of two complexes glued along the shared
// subcomplex C generated by the identified vertices. Computed as disjoint
// union, then quotient by the vertex identifications (`from` indexes B, `to`
// indexes A), then — when deduplicate is set — a bottom-up cascade
// identifying parallel cells dimension by dimension, which extends C upward
// and produces conformity along the shared interface.
//
// The vertex identifications are the geometric input (nfempy's
// vertex_with_same_geometry_q); everything after that is combinatorial. Set
// deduplicate=false when distinct cells over the same boundary must survive
// (e.g. two BRep curves spanning the same vertex pair), and quotient
// explicitly instead.
//
// Logically collective: every rank participates, supplying the vertex
// identifications it owns. P=1 today.
inline PushoutResult pushout(const Complex& a, const Complex& b,
                             const std::vector<Identification>& vertex_identifications,
                             bool deduplicate = true) {
  DisjointUnionResult du = disjoint_union(a, b);
  const int dim = du.complex.dim();

  std::vector<std::vector<Identification>> idents(static_cast<std::size_t>(dim) + 1);
  const Index shift = a.count(0);
  for (const Identification& id : vertex_identifications) {
    idents[0].push_back({static_cast<Index>(id.from + shift), id.to, id.rel_sign});
  }

  QuotientResult q = quotient(du.complex, idents);
  Complex cur = std::move(q.complex);
  ChainMap total = std::move(q.map);

  if (deduplicate) {
    for (int k = 1; k <= dim; ++k) {
      std::vector<Identification> dups = find_parallel_cells(cur, k);
      if (dups.empty()) continue;
      std::vector<std::vector<Identification>> ids(static_cast<std::size_t>(dim) + 1);
      ids[static_cast<std::size_t>(k)] = std::move(dups);
      QuotientResult q2 = quotient(cur, ids);
      cur = std::move(q2.complex);
      total = compose(total, q2.map);
    }
  }

  PushoutResult res{std::move(cur), {}, {}};
  res.a_map = compose(du.a_map, total);
  res.b_map = compose(du.b_map, total);
  return res;
}

}  // namespace graphos
