#pragma once

#include <utility>
#include <vector>

#include "graphos/core/coboundary.hpp"
#include "graphos/core/complex.hpp"
#include "graphos/core/marker.hpp"
#include "graphos/exec/forall.hpp"
#include "graphos/exec/memory.hpp"

namespace graphos {

struct SubcomplexResult {
  Complex complex;
  // parent → sub: invalid_index outside the subcomplex
  ChainMap map;
  // sub → parent, total. Restricting a cochain is a gather through it.
  ChainMap embedding;
};

// cl(S) for the marked S, compacted into its own complex: the extraction
// dual of star_deletion. Fracture networks after a cut, material regions, ∂K,
// and the k-skeleton (mark everything of dimension ≤ k) are all instances.
//
// The subcomplex is generated by the union of all ranks' marks; the closure
// crosses partition boundaries through the halo.
//
// Incidence numbers are inherited, so ∂∘∂ = 0 holds whenever it holds in the
// parent.
namespace detail {

template <typename GetCoboundary>
SubcomplexResult subcomplex_via(const Complex& c, const Marker& cells, GetCoboundary&& get_cob) {
  const int dim = c.dim();
  cells.validate_for(c);

  // mark: keep[k][i] = 1 where S selects
  std::vector<exec::Buffer<Index>> keep;
  keep.reserve(static_cast<std::size_t>(dim) + 1);
  for (int k = 0; k <= dim; ++k) {
    keep.emplace_back(static_cast<std::size_t>(c.count(k)));
    Index* g = keep[static_cast<std::size_t>(k)].data();
    const char* mf = cells.flags(k).data();
    exec::forall(c.count(k), [=](Index i) { g[i] = mf[i] ? 1 : 0; });
  }

  // downward closure, gathered through δ: a cell is kept if marked or if any
  // coface is kept. Top-down, so cofaces are final when a stratum is
  // processed, and the gather keeps every write private to one cell.
  for (int k = dim - 1; k >= 0; --k) {
    decltype(auto) cob = get_cob(k);
    const Index* offs = cob.offsets.data();
    const Index* cof = cob.indices.data();
    const Index* up = keep[static_cast<std::size_t>(k) + 1].data();
    Index* kk = keep[static_cast<std::size_t>(k)].data();
    exec::forall(c.count(k), [=](Index f) {
      if (kk[f]) return;
      for (Index m = offs[f]; m < offs[f + 1]; ++m) {
        if (up[cof[m]]) {
          kk[f] = 1;
          return;
        }
      }
    });
  }

  // scan: compact survivors into contiguous indices
  ChainMap map = ChainMap::sized(c.counts());
  std::vector<Index> kept_counts(static_cast<std::size_t>(dim) + 1, 0);
  for (int k = 0; k <= dim; ++k) {
    const std::size_t sk = static_cast<std::size_t>(k);
    const Index n = c.count(k);
    exec::Buffer<Index> pos(static_cast<std::size_t>(n));
    kept_counts[sk] = exec::exclusive_scan(keep[sk].data(), pos.data(), n);
    Index* mi = map.index[sk].data();
    const Index* g = keep[sk].data();
    const Index* pp = pos.data();
    exec::forall(n, [=](Index i) { mi[i] = g[i] ? pp[i] : invalid_index; });
  }

  // the embedding inverts the map on survivors; targets are distinct
  ChainMap embedding = ChainMap::sized(kept_counts);
  for (int k = 0; k <= dim; ++k) {
    const std::size_t sk = static_cast<std::size_t>(k);
    Index* ei = embedding.index[sk].data();
    const Index* mi = map.index[sk].data();
    exec::forall(c.count(k), [=](Index i) {
      if (mi[i] != invalid_index) ei[mi[i]] = i;
    });
  }

  // scatter: assemble ∂_k. Faces of kept cells are kept by construction, so
  // every reference resolves.
  std::vector<BoundaryOperator> strata(static_cast<std::size_t>(dim) + 1);
  for (int k = 1; k <= dim; ++k) {
    const std::size_t sk = static_cast<std::size_t>(k);
    const BoundaryOperator& bnd = c.boundary(k);
    const Index n = c.count(k);
    const Index nn = kept_counts[sk];
    BoundaryOperator& out = strata[sk];
    out.offsets.assign(static_cast<std::size_t>(nn) + 1, 0);

    const Index* g = keep[sk].data();
    const Index* mi = map.index[sk].data();
    const Index* offs = bnd.offsets.data();
    Index* no = out.offsets.data();
    exec::forall(n, [=](Index e) {
      if (g[e]) no[mi[e] + 1] = offs[e + 1] - offs[e];
    });
    exec::inclusive_scan_inplace(no, nn + 1);

    out.indices.resize(static_cast<std::size_t>(no[nn]));
    out.signs.resize(static_cast<std::size_t>(no[nn]));
    const Index* faces = bnd.indices.data();
    const Sign* sg = bnd.signs.data();
    const Index* mlo = map.index[sk - 1].data();
    Index* oidx = out.indices.data();
    Sign* osg = out.signs.data();
    exec::forall(n, [=](Index e) {
      if (!g[e]) return;
      Index w = no[mi[e]];
      for (Index m = offs[e]; m < offs[e + 1]; ++m) {
        oidx[w] = mlo[faces[m]];
        osg[w] = sg[m];
        ++w;
      }
    });
  }

  return SubcomplexResult{Complex(std::move(kept_counts), std::move(strata)), std::move(map),
                          std::move(embedding)};
}

}  // namespace detail

inline SubcomplexResult subcomplex(const Complex& c, const Marker& cells) {
  return detail::subcomplex_via(c, cells, [&](int k) { return coboundary(c, k); });
}

// As above with precomputed cob[k] = δ_k. Extracting many subcomplexes from
// one parent computes δ once rather than per extraction, which otherwise
// dominates the closure gather.
inline SubcomplexResult subcomplex(const Complex& c, const Marker& cells,
                                   const std::vector<CoboundaryOperator>& cob) {
  if (static_cast<int>(cob.size()) < c.dim()) {
    throw std::invalid_argument("subcomplex: need coboundary operators for k = 0..dim-1");
  }
  return detail::subcomplex_via(c, cells, [&](int k) -> const CoboundaryOperator& {
    return cob[static_cast<std::size_t>(k)];
  });
}

}  // namespace graphos
