#pragma once

#include <algorithm>
#include <map>
#include <vector>

#include "graphos/core/complex.hpp"
#include "graphos/core/marker.hpp"

namespace graphos {

namespace detail {

// rank of ∂_k over Z₂ by column reduction, optionally restricted to the
// relative chain complex C_*(K)/C_*(A): columns of A-cells and entries at
// A-faces are struck out.
inline Index rank_z2(const Complex& c, int k, const std::vector<std::vector<char>>* excluded) {
  const auto symdiff = [](const std::vector<Index>& a, const std::vector<Index>& b) {
    std::vector<Index> out;
    std::set_symmetric_difference(a.begin(), a.end(), b.begin(), b.end(), std::back_inserter(out));
    return out;
  };

  const BoundaryOperator& bnd = c.boundary(k);
  const std::vector<char>* ex_hi =
      excluded != nullptr ? &(*excluded)[static_cast<std::size_t>(k)] : nullptr;
  const std::vector<char>* ex_lo =
      excluded != nullptr ? &(*excluded)[static_cast<std::size_t>(k) - 1] : nullptr;

  Index rank = 0;
  std::map<Index, std::vector<Index>> pivot;  // lowest face -> reduced column
  for (Index e = 0; e < c.count(k); ++e) {
    if (ex_hi != nullptr && (*ex_hi)[static_cast<std::size_t>(e)]) continue;
    std::vector<Index> col;
    for (Index m = bnd.offsets[e]; m < bnd.offsets[e + 1]; ++m) {
      const Index f = bnd.indices[m];
      if (ex_lo != nullptr && (*ex_lo)[static_cast<std::size_t>(f)]) continue;
      col.push_back(f);
    }
    std::sort(col.begin(), col.end());
    std::vector<Index> reduced;
    for (std::size_t i = 0; i < col.size();) {
      std::size_t j = i;
      while (j < col.size() && col[j] == col[i]) ++j;
      if ((j - i) % 2 == 1) reduced.push_back(col[i]);
      i = j;
    }
    while (!reduced.empty()) {
      const auto it = pivot.find(reduced.back());
      if (it == pivot.end()) break;
      reduced = symdiff(reduced, it->second);
    }
    if (!reduced.empty()) {
      pivot.emplace(reduced.back(), std::move(reduced));
      ++rank;
    }
  }
  return rank;
}

inline std::vector<Index> betti_z2(const Complex& c,
                                   const std::vector<std::vector<char>>* excluded) {
  const int dim = c.dim();
  std::vector<Index> rank(static_cast<std::size_t>(dim) + 2, 0);
  for (int k = 1; k <= dim; ++k) {
    rank[static_cast<std::size_t>(k)] = rank_z2(c, k, excluded);
  }
  std::vector<Index> betti(static_cast<std::size_t>(dim) + 1, 0);
  for (int k = 0; k <= dim; ++k) {
    const std::size_t sk = static_cast<std::size_t>(k);
    Index n = c.count(k);
    if (excluded != nullptr) {
      for (const char f : (*excluded)[sk]) n -= (f != 0);
    }
    betti[sk] = n - rank[sk] - rank[sk + 1];
  }
  return betti;
}

}  // namespace detail

// The Betti numbers over Z₂: β_k = dim H_k(C; Z₂) = count(k) − rank ∂_k −
// rank ∂_{k+1}, ranks computed by column reduction mod 2 (the standard
// boundary-matrix reduction). β₀ counts connected components, β₁
// independent tunnels, β₂ enclosed cavities — the numbers that control
// the dimension of harmonic fields and hence well-posedness of mixed
// formulations on fractured/multiply-connected domains.
//
// Z₂ coefficients are orientation-independent (signs are irrelevant mod 2).
// Honest caveat: β_k(Z₂) ≥ β_k(ℝ), with equality unless the domain has
// 2-torsion (Klein bottles, projective planes — not reservoir geometry);
// Σ (−1)^k β_k = χ holds over any field and is a built-in self-check.
//
// Collective. P=1 today.
inline std::vector<Index> betti_numbers_z2(const Complex& c) {
  return detail::betti_z2(c, nullptr);
}

// RELATIVE Betti numbers β_k(K, A; Z₂), with A the closed subcomplex
// generated by the marked cells (the closure is taken internally, so any
// marker defines a valid A). This is the invariant of the excision
// isomorphism H_k(K, st S) ≅ H_k(K∖st S, frontier): both sides are
// computable and comparable. H_k(K, ∅) recovers the absolute numbers;
// H_k(disk, ∂disk) = {0,...,0,1} is the classic sanity check.
//
// Collective. P=1 today.
inline std::vector<Index> betti_numbers_z2(const Complex& c, const Marker& rel) {
  rel.validate_for(c);
  const int dim = c.dim();
  std::vector<std::vector<char>> in_a(static_cast<std::size_t>(dim) + 1);
  for (int k = 0; k <= dim; ++k) in_a[static_cast<std::size_t>(k)] = rel.flags(k);
  for (int k = dim; k >= 1; --k) {
    const BoundaryOperator& bnd = c.boundary(k);
    for (Index e = 0; e < c.count(k); ++e) {
      if (!in_a[static_cast<std::size_t>(k)][static_cast<std::size_t>(e)]) continue;
      for (Index m = bnd.offsets[e]; m < bnd.offsets[e + 1]; ++m) {
        in_a[static_cast<std::size_t>(k) - 1][static_cast<std::size_t>(bnd.indices[m])] = 1;
      }
    }
  }
  return detail::betti_z2(c, &in_a);
}

}  // namespace graphos
